version: "3.8"
networks:
  prabin_redpanda_network:
    driver: bridge
# volumes:
#   prabin-redpanda: null
services:
  prabin-redpanda:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:29092
      # Address the broker advertises to clients that connect to the Kafka API.
      # Use the internal addresses to connect to the Redpanda brokers'
      # from inside the same Docker network.
      # Use the external addresses to connect to the Redpanda brokers'
      # from outside the Docker network.
      - --advertise-kafka-addr internal://prabin-redpanda:9092,external://localhost:29092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:28082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://prabin-redpanda:8082,external://localhost:28082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:28081
      # Redpanda brokers use the RPC API to communicate with each other internally.
      - --rpc-addr prabin-redpanda:33145
      - --advertise-rpc-addr prabin-redpanda:33145
      # Mode dev-container uses well-known configuration properties for development in containers.
      - --mode dev-container
      # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.5
    container_name: prabin-redpanda
    # volumes:
    #   - prabin-redpanda:/var/lib/redpanda/data
    networks:
      - prabin_redpanda_network
    ports:
      - 28081:28081
      - 28082:28082
      - 29092:29092
      - 29644:9644
  prabin-console:
    container_name: prabin_redpanda-console
    image: docker.redpanda.com/redpandadata/console:v3.1.1
    networks:
      - prabin_redpanda_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["prabin-redpanda:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://prabin-redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://prabin-redpanda:9644"]
    ports:
      - 2048:8080
    depends_on:
      - prabin-redpanda